### ISSUE TITLE
App just closes if proxer is down

### ISSUE THREAD

**Issue by Skgland** [inv3rse/ProxerTv#1]
The app just closed, it seams to be related to proxer.me beeing down, still an error message to inform the user would be nice instead of just silently closing.

**Comment by inv3rse** [comment]
I expected all rows to simply stay empty. Thanks for reporting, I will look into it.

**Comment by Skgland** [comment]
well proxer is available again but app won't open longer than a split second, seams therefor no relatet

**Comment by inv3rse** [comment]
The app will cache the response from the server for about 4 hours on the start page. I guess the cloudflare offline response is not handled correctly and is currently still served from cache. Clearing it might help.

**Comment by Skgland** [comment]
reinstalling it didn't help, also tried clearing the cache

**Comment by inv3rse** [comment]
I am just on my phone currently. Cloudflare ddos protection seems to be still active. I guess they changed something and the code to bypass it crashes.

**Comment by Skgland** [comment]
ok, well i need to go to bed now either way its almost midnight
